# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: yuichirose.github.io
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
description: >-
  Yuichi Hirose's webpage
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: solidknit
github_username: yuichirose

# Build settings
# theme: minima
theme: just-the-docs

plugins:
  - jekyll-feed

logo: "/assets/images/solidknit-sandals.png"
favicon_ico: "/assets/images/solidknit-sandals-favicon.png"

just_the_docs:
  custom_css: "assets/css/custom-styles.scss"

nav_external_links:
  - title: Top
    url: /#top
    hide_icon: true # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: Research
    url: /#research
    hide_icon: true
    opens_in_new_tab: false
  - title: Course Projects
    url: /#course-projects
    hide_icon: true
    opens_in_new_tab: false
  - title: Weekend Projects
    url: /#weekend-projects
    hide_icon: true
    opens_in_new_tab: false
  - title: Patent
    url: /#patent
    hide_icon: true
    opens_in_new_tab: false
  - title: Grants, Scholarship & Awards
    url: /#grants-scholarship--awards
    hide_icon: true
    opens_in_new_tab: false
  - title: Talks & Exhibition
    url: /#talks--exhibition
    hide_icon: true
    opens_in_new_tab: false
  - title: Miscellanea
    url: /#miscellanea
    hide_icon: true
    opens_in_new_tab: false

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: green

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/